name: "Set up Java tooling"
description: "Define the Java environment to use"
runs:
  using: "composite"
  steps:
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: corretto
