name: Publish Libraries to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: corretto
    - name: Publish package
      run: sbt test publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}