name: Publish Libraries to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up java
      uses: ./.github/actions/setup-java
    - name: Build and Publish package
      run: sbt test publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
